export const SKILL_LINKS: Record<string, string> = {
  Angular: 'https://angular.io/',
  'Angular 14': 'https://angular.io/',
  'Angular 16': 'https://angular.io/',
  Electron: 'https://www.electronjs.org/',
  SCSS: 'https://sass-lang.com/',
  'Material Design': 'https://m3.material.io/',
  Webstorm: 'https://www.jetbrains.com/webstorm/',
  Gitlab: 'https://about.gitlab.com/',
  OneLogin: 'https://www.onelogin.com/',
  GraphQL: 'https://graphql.org/',
  Jira: 'https://www.atlassian.com/software/jira',
  PHP: 'https://www.php.net/',
  JS: 'https://developer.mozilla.org/docs/Web/JavaScript',
  TailwindCSS: 'https://tailwindcss.com/',
  Bitbucket: 'https://bitbucket.org/',
  PGSQL: 'https://www.postgresql.org/',
  SAML2: 'https://en.wikipedia.org/wiki/SAML_2.0',
  DaisyUi: 'https://daisyui.com/',
  NestJs: 'https://nestjs.com/',
  GIT: 'https://git-scm.com/',
  Drupal: 'https://www.drupal.org/',
  Bootstrap: 'https://getbootstrap.com/',
  'Material Bootstrap': 'https://mdbootstrap.com/',
  Linux: 'https://www.linux.org/',
  //Recherche: 'https://fr.wikipedia.org/wiki/Recherche',
  Montage: 'https://www.adobe.com/fr/products/premiere.html',
  //'Enregistrement audio': 'https://fr.wikipedia.org/wiki/Enregistrement_sonore',
  //Ecriture: 'https://fr.wikipedia.org/wiki/%C3%89criture',
  //Réalisation: 'https://fr.wikipedia.org/wiki/R%C3%A9alisation',
  HTML: 'https://developer.mozilla.org/docs/Web/HTML',
  CSS: 'https://developer.mozilla.org/docs/Web/CSS'
};
